/**
 * Single canonical mapping from a decision string (Chinese or legacy English)
 * to a display action. Previously duplicated in Analysis.tsx, Reports.tsx and
 * DecisionCard.tsx with inconsistent semantics (Reports mapped BUY→add while
 * DecisionCard mapped BUY→buy); all call sites now share this one function.
 */
export type DecisionAction =
    | 'buy'
    | 'sell'
    | 'hold'
    | 'add'
    | 'reduce'
    | 'watch'
    | 'no_trade'
    | 'invalid'
    | 'none'

export function parseDecisionAction(decision?: string | null): DecisionAction | undefined {
    if (!decision) return undefined
    const d = decision.toUpperCase()
    if (d.includes('INVALID_RUN') || d.includes('DATA_ERROR') || d.includes('无效运行')) {
        return 'invalid'
    }
    // Prefer exact INVALID over generic "INVALID" substring after INVALID_RUN handled.
    if (d === 'INVALID' || d.includes('INVALID')) {
        return 'invalid'
    }
    if (d.includes('NO_TRADE') || d.includes('不交易') || d.includes('ABSTAIN') || d.includes('弃权')) {
        return 'no_trade'
    }
    if (d.includes('WAIT') || d.includes('WATCH') || d.includes('观望')) return 'watch'
    if (d.includes('SELL') || d.includes('卖出')) return 'sell'
    if (d.includes('REDUCE') || d.includes('减持')) return 'reduce'
    if (d.includes('HOLD') || d.includes('持有') || d.includes('中性')) return 'hold'
    if (d.includes('ADD') || d.includes('增持')) return 'add'
    if (d.includes('BUY') || d.includes('买入')) return 'buy'
    if (d === 'N/A' || d === 'NA') return 'no_trade'
    return undefined
}

export function sanitizeReportMarkdown(text?: string | null): string {
    if (!text) return ''
    return text
        .replace(/<!--\s*VERDICT:[^>]*-->/gi, '') // strip machine-readable verdict tag
        .replace(/FINAL TRANSACTION PROPOSAL:\s*\**\s*BUY\s*\**/gi, '最终交易建议：买入')
        .replace(/FINAL TRANSACTION PROPOSAL:\s*\**\s*SELL\s*\**/gi, '最终交易建议：卖出')
        .replace(/FINAL TRANSACTION PROPOSAL:\s*\**\s*HOLD\s*\**/gi, '最终交易建议：观望')
        .replace(/FINAL VERDICT:\s*/gi, '最终裁决：')
        .replace(/HOLD with Conditional Trigger/gi, '观望（条件触发）')
        .replace(/BUY with Conditional Trigger/gi, '买入（条件触发）')
        .replace(/SELL with Conditional Trigger/gi, '卖出（条件触发）')
}

export interface Verdict {
    direction: string
    reason: string
}

// Map English direction values (en.py prompts) to Chinese display labels
const DIRECTION_ALIAS: Record<string, string> = {
    BULLISH:       '看多',
    LEAN_BULLISH:  '偏多',
    BEARISH:       '看空',
    LEAN_BEARISH:  '偏空',
    NEUTRAL:       '中性',
    CAUTIOUS:      '谨慎',  // 向后兼容旧报告
    'N/A':         '不适用',
    NA:            '不适用',
    BULL:          '看多',
    BEAR:          '看空',
}

// English directions only ever come from the legacy en.py prompt set. New
// reports persist Chinese directions (看多/偏多/中性/偏空/看空), so an English
// direction is a reliable "旧版报告" signal available even on list rows that do
// not carry the full markdown sections.
const LEGACY_ENGLISH_DIRECTIONS = new Set([
    'BULLISH',
    'LEAN_BULLISH',
    'BEARISH',
    'LEAN_BEARISH',
    'NEUTRAL',
    'CAUTIOUS',
])

const REPORT_CONTENT_KEYS = [
    'market_report',
    'sentiment_report',
    'news_report',
    'fundamentals_report',
    'macro_report',
    'smart_money_report',
    'volume_price_report',
    'game_theory_report',
    'investment_plan',
    'trader_investment_plan',
    'final_trade_decision',
] as const

const ENGLISH_WORD_RE = /[A-Za-z]{2,}/g
const CJK_CHAR_RE = /[一-鿿]/g

export function isLegacyEnglishDirection(direction?: string | null): boolean {
    if (!direction) return false
    return LEGACY_ENGLISH_DIRECTIONS.has(direction.trim().toUpperCase())
}

/**
 * Display-layer mapping for the report direction. New reports persist Chinese
 * directions (看多/偏多/中性/偏空/看空); pre-localization legacy reports carry
 * English values (BULLISH/LEAN_BULLISH/…). Map those to Chinese so a legacy
 * report renders consistently instead of leaking English on the DecisionCard.
 */
export function localizeDirection(direction?: string | null): string | null {
    if (!direction) return null
    const alias = DIRECTION_ALIAS[direction.trim().toUpperCase()]
    return alias ?? direction
}

/**
 * Content-based heuristic for reports generated by the old English prompt set.
 *
 * Legacy reports are written in English prose, while current reports are
 * Chinese with at most scattered English jargon (BUY/SELL/HOLD, MACD, ROE…).
 * A report counts as legacy when it carries a substantial amount of English
 * text — either an absolute volume of English words, or a volume that clearly
 * dominates the Chinese characters present.
 */
export function detectLegacyEnglishContent(text: string): boolean {
    const englishWords = text.match(ENGLISH_WORD_RE)?.length ?? 0
    if (englishWords === 0) return false
    if (englishWords >= 40) return true
    const cjkChars = text.match(CJK_CHAR_RE)?.length ?? 0
    if (cjkChars === 0) return englishWords >= 12
    return englishWords >= 12 && englishWords * 4 >= cjkChars
}

/**
 * Minimal shape accepted by {@link isLegacyEnglishReport}. Both the list `Report`
 * (direction only) and the detail `ReportDetail` (direction + sections) satisfy
 * it structurally.
 */
export interface LegacyReportCandidate {
    direction?: string | null
    market_report?: string
    sentiment_report?: string
    news_report?: string
    fundamentals_report?: string
    macro_report?: string
    smart_money_report?: string
    volume_price_report?: string
    game_theory_report?: string
    investment_plan?: string
    trader_investment_plan?: string
    final_trade_decision?: string
}

/**
 * True when the report was generated by the pre-Chinese-localization engine and
 * is still stored in English. Accepts either the list shape (direction only) or
 * the detail shape (direction + markdown sections).
 */
export function isLegacyEnglishReport(report: LegacyReportCandidate): boolean {
    if (isLegacyEnglishDirection(report.direction)) return true
    const content = REPORT_CONTENT_KEYS
        .map(key => (typeof report[key] === 'string' ? (report[key] as string) : ''))
        .join('\n')
    if (!content.trim()) return false
    return detectLegacyEnglishContent(content)
}

/**
 * DAV-1271 W1: explain the "方向偏空/偏多但执行动作为观望" combination.
 *
 * Pure display layer: when the pipeline flags the analysis as VALID but the
 * trade action was downgraded to WAIT and the manager direction is still
 * directional, surface a one-line reason instead of the raw status pair.
 */
export interface WaitDowngradeContext {
    analysis_status?: string | null
    trade_action?: string | null
    direction?: string | null
    confirmation_state?: string | null
    reason_codes?: ReadonlyArray<string> | null
}

const UPSTREAM_BLOCKED_RE = /^\s*上游决策状态为/

/** Sections whose generated text may be the upstream-blocked placeholder. */
const UPSTREAM_PLACEHOLDER_SECTIONS = new Set([
    'trader_investment_plan',
    'final_trade_decision',
])

export function buildWaitDowngradeExplanation(
    ctx: WaitDowngradeContext | null | undefined,
    opts?: { short?: boolean },
): string | null {
    if (!ctx) return null
    if (String(ctx.analysis_status || '').trim().toUpperCase() !== 'VALID') return null
    if (String(ctx.trade_action || '').trim().toUpperCase() !== 'WAIT') return null
    const localized = localizeDirection(ctx.direction)
    const lean =
        localized === '看多' || localized === '偏多' ? '看多'
        : localized === '看空' || localized === '偏空' ? '看空'
        : null
    if (!lean) return null
    // DAV-1271 rework: WAIT does not always mean the core claims were
    // under-verified (the manager may pick WAIT directly, VPA candidates,
    // pending signals…). Only confirmation states that provably carry a
    // verification shortfall may claim it; anything else stays neutral.
    const conf = String(ctx.confirmation_state || '').trim().toUpperCase()
    if (opts?.short) {
        if (conf === 'PARTIAL') {
            return `研究团队倾向${lean}，但核心论据只部分确认，按规则保持观望。`
        }
        if (conf === 'UNRESOLVED') {
            return `研究团队倾向${lean}，但核心论据尚未确认，按规则保持观望。`
        }
        return `研究团队倾向${lean}，但本次执行动作为观望（WAIT）。`
    }
    if (conf === 'PARTIAL') {
        return `研究团队倾向${lean}，但核心论据只部分核实（部分确认），按规则不给出买卖指令，执行动作为观望。`
    }
    if (conf === 'UNRESOLVED') {
        return `研究团队倾向${lean}，但核心论据尚未核实，按规则不给出买卖指令，执行动作为观望。`
    }
    // CONFIRMED / missing / unknown: no machine-mappable reason — state the
    // downgrade fact only, never invent a cause (零幻觉).
    return `研究团队倾向${lean}，但本次执行动作为观望（WAIT），未给出买卖指令。`
}

/* ─── DAV-1283 D3: report-list decision label ──────────────────────────────
 * Previously `parseDecision` lived inside Reports.tsx and silently rendered
 * empty columns as "观望". Moved here so the label contract is testable.
 */
export interface ReportListDecisionMeta {
    analysis_status?: string | null
    trade_action?: string | null
    direction?: string | null
    reason_codes?: ReadonlyArray<string> | null
}

export type ReportListAction =
    | 'add'
    | 'reduce'
    | 'hold'
    | 'watch'
    | 'no_trade'
    | 'invalid'
    | 'none'

export function resolveReportListDecision(
    decisionText?: string,
    meta?: ReportListDecisionMeta,
): { action: ReportListAction; label: string } {
    const status = (meta?.analysis_status || '').toUpperCase()
    const trade = (meta?.trade_action || decisionText || '').toUpperCase()
    if (status === 'INVALID_RUN' || status === 'DATA_ERROR' || trade.includes('INVALID')) {
        return { action: 'invalid', label: '无效运行' }
    }
    if (status === 'ABSTAIN') {
        return { action: 'no_trade', label: '弃权/不交易' }
    }
    if (trade === 'NO_TRADE' || trade.includes('NO_TRADE')) {
        // A gate-downgraded NO_TRADE is not a plain "不交易".
        const gated = (meta?.reason_codes ?? []).some(c => c === PRICE_GATE_BLOCKED_CODE)
        return { action: 'no_trade', label: gated ? '不交易（价格未通过）' : '不交易' }
    }
    if (trade === 'WAIT' || status === 'PARTIAL') {
        return { action: 'watch', label: status === 'PARTIAL' ? '部分可用/观望' : '观望' }
    }
    // Empty columns mean "未记录", never a fake "观望".
    if (!decisionText && !trade) return { action: 'none', label: '未记录' }
    const action = parseDecisionAction(meta?.trade_action || decisionText)
    if (action === 'invalid') return { action: 'invalid', label: '无效运行' }
    if (action === 'no_trade') return { action: 'no_trade', label: '不交易' }
    if (action === 'watch') return { action: 'watch', label: '观望' }
    if (action === 'buy' || action === 'add') return { action: 'add', label: '增持' }
    if (action === 'sell' || action === 'reduce') return { action: 'reduce', label: '减持' }
    return { action: 'hold', label: '持有' }
}

/* ─── DAV-1283 D4: price-basis-gate downgrade note ─────────────────────────
 * When the manager's action (BUY/SELL/HOLD) was downgraded to NO_TRADE by the
 * price-basis gate, every surface must explain it instead of letting the
 * pre-gate text ("卖出") stand alone.
 */
export const PRICE_GATE_BLOCKED_CODE = 'price_basis_gate_blocked'

export interface PriceGateViolation {
    kind?: string
    source?: string | null
    detail?: string | null
    ref_ids?: Array<string | null>
}

export interface PriceGateDecisionStatus {
    trade_action?: string | null
    reason_codes?: ReadonlyArray<string> | null
    failed_checks?: ReadonlyArray<string> | null
}

export interface PriceGateSlice {
    trade_action?: string | null
    reason_codes?: ReadonlyArray<string> | null
    decision_status?: PriceGateDecisionStatus | null
    price_basis_gate?: { status?: string; violations?: PriceGateViolation[] } | null
}

/** Structural source accepted by {@link resolvePriceGateDowngrade}: either an
 * AnalysisReport-shaped object (its own fields are the result_data) or an API
 * report row carrying `result_data`. */
export interface PriceGateSource {
    trade_action?: string | null
    decision?: string | null
    pre_gate_trade_action?: string | null
    reason_codes?: ReadonlyArray<string> | null
    decision_status?: PriceGateDecisionStatus | null
    short_term?: PriceGateSlice | null
    price_basis_gate?: { status?: string; violations?: PriceGateViolation[] } | null
    result_data?: PriceGateSource | null
}

const GATE_PRE_ACTION_LABEL: Record<string, string> = {
    BUY: '买入',
    SELL: '卖出',
    HOLD: '持有',
}

const PRICE_NUMBER_RE = /\d+(?:\.\d+)?/g
const MAX_GATE_PRICE_SAMPLES = 3

/**
 * Detect a price-basis-gate downgrade: final (post-gate) action is NO_TRADE
 * while the manager's pre-gate action was directional. Returns the pre-gate
 * action plus up to 3 unverifiable price samples from the gate violations.
 */
export function resolvePriceGateDowngrade(
    src: PriceGateSource | null | undefined,
): { managerAction: 'BUY' | 'SELL' | 'HOLD'; prices: string[] } | null {
    if (!src) return null
    const rd: PriceGateSource = src.result_data ?? src
    const slice: PriceGateSlice | null =
        rd.short_term && typeof rd.short_term === 'object' ? rd.short_term : null
    const postAction = String(
        slice?.trade_action ??
        slice?.decision_status?.trade_action ??
        src.trade_action ??
        rd.trade_action ??
        '',
    ).toUpperCase()
    if (postAction !== 'NO_TRADE') return null
    const codes: ReadonlyArray<string> = [
        ...(slice?.decision_status?.reason_codes ?? []),
        ...(slice?.decision_status?.failed_checks ?? []),
        ...(slice?.reason_codes ?? []),
        ...(src.reason_codes ?? []),
        ...(rd.reason_codes ?? []),
        ...(rd.decision_status?.reason_codes ?? []),
        ...(rd.decision_status?.failed_checks ?? []),
    ]
    const gate = slice?.price_basis_gate ?? rd.price_basis_gate ?? null
    const blocked =
        gate?.status === 'blocked' || codes.some(c => c === PRICE_GATE_BLOCKED_CODE)
    if (!blocked) return null
    // Pre-gate manager action: explicit field (new reports) first, then the
    // top-level trade_action/decision of legacy payloads which still hold the
    // pre-gate value. Only directional actions count (the gate only ever
    // downgrades BUY/SELL/HOLD).
    const candidates = [
        rd.pre_gate_trade_action,
        src.pre_gate_trade_action,
        rd.trade_action,
        rd.decision,
        src.decision,
    ]
    const managerAction = candidates
        .map(c => String(c || '').toUpperCase())
        .find(c => c === 'BUY' || c === 'SELL' || c === 'HOLD') as
        | 'BUY'
        | 'SELL'
        | 'HOLD'
        | undefined
    if (!managerAction) return null
    const prices: string[] = []
    for (const violation of gate?.violations ?? []) {
        // Strip ref-id tokens (pr-131 / (pr-131)) so ids never read as prices.
        const detail = (typeof violation?.detail === 'string' ? violation.detail : '')
            .replace(/\(\s*pr-[^)]*\)/gi, ' ')
            .replace(/pr-\d+/gi, ' ')
        for (const match of detail.matchAll(PRICE_NUMBER_RE)) {
            if (!prices.includes(match[0])) prices.push(match[0])
            if (prices.length >= MAX_GATE_PRICE_SAMPLES) break
        }
        if (prices.length >= MAX_GATE_PRICE_SAMPLES) break
    }
    return { managerAction, prices }
}

/** One-line downgrade note shared by the completion card, the detail banner
 * and the trader/risk sections. */
export function buildPriceGateDowngradeNote(
    src: PriceGateSource | null | undefined,
): string | null {
    const downgrade = resolvePriceGateDowngrade(src)
    if (!downgrade) return null
    const pricePart = downgrade.prices.length
        ? `（如：${downgrade.prices.join('、')} 元）`
        : ''
    return `研究团队建议${GATE_PRE_ACTION_LABEL[downgrade.managerAction]}，但报告中有价格无法核实来源${pricePart}，按规则不执行，最终动作为不交易。`
}

/**
 * Replace the generated "上游决策状态为 VALID/WAIT：…" placeholder text of the
 * trader / risk sections with a human-readable downgrade explanation, when the
 * report's decision status matches the WAIT-downgrade shape. Returns the
 * original content untouched in every other case (no status context, no
 * downgrade, or non-placeholder text).
 */
export function substituteUpstreamBlockedPlaceholder(
    section: string,
    content: string | null | undefined,
    ctx: WaitDowngradeContext | null | undefined,
): string {
    const text = content || ''
    if (!UPSTREAM_PLACEHOLDER_SECTIONS.has(section) || !UPSTREAM_BLOCKED_RE.test(text)) {
        return text
    }
    const explanation = buildWaitDowngradeExplanation(ctx, { short: true })
    return explanation || text
}

/**
 * Extract the structured verdict embedded by the agent as an HTML comment.
 * Format: <!-- VERDICT: {"direction": "...", "reason": "..."} -->
 */
export function extractVerdict(text?: string | null): Verdict | null {
    if (!text) return null
    const m = text.match(/<!--\s*VERDICT:\s*(\{[^>]+\})\s*-->/)
    if (!m) return null
    try {
        const parsed = JSON.parse(m[1]) as { direction?: string; reason?: string }
        if (!parsed.direction || !parsed.reason) return null
        const direction = DIRECTION_ALIAS[parsed.direction.toUpperCase()] ?? parsed.direction
        return { direction, reason: parsed.reason.trim().slice(0, 42) }
    } catch {
        return null
    }
}
