/**
 * Single canonical mapping from a decision string (Chinese or legacy English)
 * to a display action. Previously duplicated in Analysis.tsx, Reports.tsx and
 * DecisionCard.tsx with inconsistent semantics (Reports mapped BUY→add while
 * DecisionCard mapped BUY→buy); all call sites now share this one function.
 */
export type DecisionAction =
    | 'buy'
    | 'sell'
    | 'hold'
    | 'add'
    | 'reduce'
    | 'watch'
    | 'no_trade'
    | 'invalid'

export function parseDecisionAction(decision?: string | null): DecisionAction | undefined {
    if (!decision) return undefined
    const d = decision.toUpperCase()
    if (d.includes('INVALID_RUN') || d.includes('DATA_ERROR') || d.includes('无效运行')) {
        return 'invalid'
    }
    // Prefer exact INVALID over generic "INVALID" substring after INVALID_RUN handled.
    if (d === 'INVALID' || d.includes('INVALID')) {
        return 'invalid'
    }
    if (d.includes('NO_TRADE') || d.includes('不交易') || d.includes('ABSTAIN') || d.includes('弃权')) {
        return 'no_trade'
    }
    if (d.includes('WAIT') || d.includes('WATCH') || d.includes('观望')) return 'watch'
    if (d.includes('SELL') || d.includes('卖出')) return 'sell'
    if (d.includes('REDUCE') || d.includes('减持')) return 'reduce'
    if (d.includes('HOLD') || d.includes('持有') || d.includes('中性')) return 'hold'
    if (d.includes('ADD') || d.includes('增持')) return 'add'
    if (d.includes('BUY') || d.includes('买入')) return 'buy'
    if (d === 'N/A' || d === 'NA') return 'no_trade'
    return undefined
}

export function sanitizeReportMarkdown(text?: string | null): string {
    if (!text) return ''
    return text
        .replace(/<!--\s*VERDICT:[^>]*-->/gi, '') // strip machine-readable verdict tag
        .replace(/FINAL TRANSACTION PROPOSAL:\s*\**\s*BUY\s*\**/gi, '最终交易建议：买入')
        .replace(/FINAL TRANSACTION PROPOSAL:\s*\**\s*SELL\s*\**/gi, '最终交易建议：卖出')
        .replace(/FINAL TRANSACTION PROPOSAL:\s*\**\s*HOLD\s*\**/gi, '最终交易建议：观望')
        .replace(/FINAL VERDICT:\s*/gi, '最终裁决：')
        .replace(/HOLD with Conditional Trigger/gi, '观望（条件触发）')
        .replace(/BUY with Conditional Trigger/gi, '买入（条件触发）')
        .replace(/SELL with Conditional Trigger/gi, '卖出（条件触发）')
}

export interface Verdict {
    direction: string
    reason: string
}

// Map English direction values (en.py prompts) to Chinese display labels
const DIRECTION_ALIAS: Record<string, string> = {
    BULLISH:       '看多',
    LEAN_BULLISH:  '偏多',
    BEARISH:       '看空',
    LEAN_BEARISH:  '偏空',
    NEUTRAL:       '中性',
    CAUTIOUS:      '谨慎',  // 向后兼容旧报告
    'N/A':         '不适用',
    NA:            '不适用',
    BULL:          '看多',
    BEAR:          '看空',
}

// English directions only ever come from the legacy en.py prompt set. New
// reports persist Chinese directions (看多/偏多/中性/偏空/看空), so an English
// direction is a reliable "旧版报告" signal available even on list rows that do
// not carry the full markdown sections.
const LEGACY_ENGLISH_DIRECTIONS = new Set([
    'BULLISH',
    'LEAN_BULLISH',
    'BEARISH',
    'LEAN_BEARISH',
    'NEUTRAL',
    'CAUTIOUS',
])

const REPORT_CONTENT_KEYS = [
    'market_report',
    'sentiment_report',
    'news_report',
    'fundamentals_report',
    'macro_report',
    'smart_money_report',
    'volume_price_report',
    'game_theory_report',
    'investment_plan',
    'trader_investment_plan',
    'final_trade_decision',
] as const

const ENGLISH_WORD_RE = /[A-Za-z]{2,}/g
const CJK_CHAR_RE = /[一-鿿]/g

export function isLegacyEnglishDirection(direction?: string | null): boolean {
    if (!direction) return false
    return LEGACY_ENGLISH_DIRECTIONS.has(direction.trim().toUpperCase())
}

/**
 * Display-layer mapping for the report direction. New reports persist Chinese
 * directions (看多/偏多/中性/偏空/看空); pre-localization legacy reports carry
 * English values (BULLISH/LEAN_BULLISH/…). Map those to Chinese so a legacy
 * report renders consistently instead of leaking English on the DecisionCard.
 */
export function localizeDirection(direction?: string | null): string | null {
    if (!direction) return null
    const alias = DIRECTION_ALIAS[direction.trim().toUpperCase()]
    return alias ?? direction
}

/**
 * Content-based heuristic for reports generated by the old English prompt set.
 *
 * Legacy reports are written in English prose, while current reports are
 * Chinese with at most scattered English jargon (BUY/SELL/HOLD, MACD, ROE…).
 * A report counts as legacy when it carries a substantial amount of English
 * text — either an absolute volume of English words, or a volume that clearly
 * dominates the Chinese characters present.
 */
export function detectLegacyEnglishContent(text: string): boolean {
    const englishWords = text.match(ENGLISH_WORD_RE)?.length ?? 0
    if (englishWords === 0) return false
    if (englishWords >= 40) return true
    const cjkChars = text.match(CJK_CHAR_RE)?.length ?? 0
    if (cjkChars === 0) return englishWords >= 12
    return englishWords >= 12 && englishWords * 4 >= cjkChars
}

/**
 * Minimal shape accepted by {@link isLegacyEnglishReport}. Both the list `Report`
 * (direction only) and the detail `ReportDetail` (direction + sections) satisfy
 * it structurally.
 */
export interface LegacyReportCandidate {
    direction?: string | null
    market_report?: string
    sentiment_report?: string
    news_report?: string
    fundamentals_report?: string
    macro_report?: string
    smart_money_report?: string
    volume_price_report?: string
    game_theory_report?: string
    investment_plan?: string
    trader_investment_plan?: string
    final_trade_decision?: string
}

/**
 * True when the report was generated by the pre-Chinese-localization engine and
 * is still stored in English. Accepts either the list shape (direction only) or
 * the detail shape (direction + markdown sections).
 */
export function isLegacyEnglishReport(report: LegacyReportCandidate): boolean {
    if (isLegacyEnglishDirection(report.direction)) return true
    const content = REPORT_CONTENT_KEYS
        .map(key => (typeof report[key] === 'string' ? (report[key] as string) : ''))
        .join('\n')
    if (!content.trim()) return false
    return detectLegacyEnglishContent(content)
}

/**
 * DAV-1271 W1: explain the "方向偏空/偏多但执行动作为观望" combination.
 *
 * Pure display layer: when the pipeline flags the analysis as VALID but the
 * trade action was downgraded to WAIT and the manager direction is still
 * directional, surface a one-line reason instead of the raw status pair.
 */
export interface WaitDowngradeContext {
    analysis_status?: string | null
    trade_action?: string | null
    direction?: string | null
    confirmation_state?: string | null
    reason_codes?: ReadonlyArray<string> | null
}

const UPSTREAM_BLOCKED_RE = /^\s*上游决策状态为/

/** Sections whose generated text may be the upstream-blocked placeholder. */
const UPSTREAM_PLACEHOLDER_SECTIONS = new Set([
    'trader_investment_plan',
    'final_trade_decision',
])

export function buildWaitDowngradeExplanation(
    ctx: WaitDowngradeContext | null | undefined,
    opts?: { short?: boolean },
): string | null {
    if (!ctx) return null
    if (String(ctx.analysis_status || '').trim().toUpperCase() !== 'VALID') return null
    if (String(ctx.trade_action || '').trim().toUpperCase() !== 'WAIT') return null
    const localized = localizeDirection(ctx.direction)
    const lean =
        localized === '看多' || localized === '偏多' ? '看多'
        : localized === '看空' || localized === '偏空' ? '看空'
        : null
    if (!lean) return null
    // DAV-1271 rework: WAIT does not always mean the core claims were
    // under-verified (the manager may pick WAIT directly, VPA candidates,
    // pending signals…). Only confirmation states that provably carry a
    // verification shortfall may claim it; anything else stays neutral.
    const conf = String(ctx.confirmation_state || '').trim().toUpperCase()
    if (opts?.short) {
        if (conf === 'PARTIAL') {
            return `研究团队倾向${lean}，但核心论据只部分确认，按规则保持观望。`
        }
        if (conf === 'UNRESOLVED') {
            return `研究团队倾向${lean}，但核心论据尚未确认，按规则保持观望。`
        }
        return `研究团队倾向${lean}，但本次执行动作为观望（WAIT）。`
    }
    if (conf === 'PARTIAL') {
        return `研究团队倾向${lean}，但核心论据只部分核实（部分确认），按规则不给出买卖指令，执行动作为观望。`
    }
    if (conf === 'UNRESOLVED') {
        return `研究团队倾向${lean}，但核心论据尚未核实，按规则不给出买卖指令，执行动作为观望。`
    }
    // CONFIRMED / missing / unknown: no machine-mappable reason — state the
    // downgrade fact only, never invent a cause (零幻觉).
    return `研究团队倾向${lean}，但本次执行动作为观望（WAIT），未给出买卖指令。`
}

/**
 * Replace the generated "上游决策状态为 VALID/WAIT：…" placeholder text of the
 * trader / risk sections with a human-readable downgrade explanation, when the
 * report's decision status matches the WAIT-downgrade shape. Returns the
 * original content untouched in every other case (no status context, no
 * downgrade, or non-placeholder text).
 */
export function substituteUpstreamBlockedPlaceholder(
    section: string,
    content: string | null | undefined,
    ctx: WaitDowngradeContext | null | undefined,
): string {
    const text = content || ''
    if (!UPSTREAM_PLACEHOLDER_SECTIONS.has(section) || !UPSTREAM_BLOCKED_RE.test(text)) {
        return text
    }
    const explanation = buildWaitDowngradeExplanation(ctx, { short: true })
    return explanation || text
}

/**
 * Extract the structured verdict embedded by the agent as an HTML comment.
 * Format: <!-- VERDICT: {"direction": "...", "reason": "..."} -->
 */
export function extractVerdict(text?: string | null): Verdict | null {
    if (!text) return null
    const m = text.match(/<!--\s*VERDICT:\s*(\{[^>]+\})\s*-->/)
    if (!m) return null
    try {
        const parsed = JSON.parse(m[1]) as { direction?: string; reason?: string }
        if (!parsed.direction || !parsed.reason) return null
        const direction = DIRECTION_ALIAS[parsed.direction.toUpperCase()] ?? parsed.direction
        return { direction, reason: parsed.reason.trim().slice(0, 42) }
    } catch {
        return null
    }
}
